# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readcounter',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.TextField(null=True, verbose_name='\u53c2\u8003\u6587\u6863'),
        ),
    ]
